version: '3.5'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8081:8080
  laravel-api:
    build:
      dockerfile: Dockerfile.api
      args:
        - DEPLOYMENT_KEY=${DEPLOYMENT_KEY}
    container_name: laravel-api
    depends_on:
      - db
  data-creator:
    build:
      dockerfile: Dockerfile.data
      args:
        - DEPLOYMENT_KEY=${DEPLOYMENT_KEY}
    container_name: data-creator
    entrypoint: ['bash', "-c", "cron -f"]
    depends_on:
      - db
      - laravel-api
  frontend:
    build:
      dockerfile: Dockerfile.front
      args:
        - DEPLOYMENT_KEY=${DEPLOYMENT_KEY}
    container_name: frontend
    environment:
      - APIURL=${APP_URL}
  proxy:
    build:
      dockerfile: Dockerfile.proxy
    container_name: proxy
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - ${PUBLISH_PORT}:443
    depends_on:
      - laravel-api
      - frontend