version: '3.5'

services:
  db:
    image: mysql
    restart: always
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8081:8080
    networks:
      backend:
        aliases:
          - adminer
  laravel-api:
    build:
      context: './stockAPI'
      args:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=db
        - DB_USERNAME=dbuser
        - DB_PASSWORD=secret
    container_name: laravel-api
    # volumes:
      # - ./stockAPI:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    networks:
      backend:
        aliases:
          - laravel-api
  data-creator:
    build:
      context: './dataCreator'
      args:
        - DB_HOST=db
        - DB_PORT=3306
        - DB_DATABASE=db
        - DB_USERNAME=dbuser
        - DB_PASSWORD=secret
    container_name: data-creator
    entrypoint: ['bash', "-c", "cron -f"]
    depends_on:
      - db
      - laravel-api
    networks:
      backend:
        aliases:
          - data-creator
networks:
  backend:
    name: backend-network
