version: '3.5'

services:
  laravel-api:
    build:
      context: './stockAPI'
      args:
        uid: ${UID}
    container_name: laravel-api
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=api
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./stockAPI:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-api

  # mysql-db:
  #   image: mysql:5.7
  #   container_name: mysql-db
  #   volumes:
  #     - ./run/var:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=securerootpassword
  #     - MYSQL_DATABASE=db
  #     - MYSQL_USER=dbuser
  #     - MYSQL_PASSWORD=secret
  #   networks:
  #     backend:
  #       aliases:
  #         - db

networks:
  backend:
    name: backend-network
